//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextOGlitch {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextOGlitch.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text&apos;O&apos;Glitch 4.0.
        ///Written on C#. Author &amp; code: t.me/russkiypoopforever.
        ///Graphics: t.me/naturalnonsense.
        ///https://github.com/DBmain/TextOGlitch.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard is empty!.
        /// </summary>
        internal static string clipboardEmpty {
            get {
                return ResourceManager.GetString("clipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text converted to Base64!.
        /// </summary>
        internal static string convertedToBaseTray {
            get {
                return ResourceManager.GetString("convertedToBaseTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Copied to clipboard..
        /// </summary>
        internal static string copiedToClipboard {
            get {
                return ResourceManager.GetString("copiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ® copied to the clipboard!.
        /// </summary>
        internal static string copyleft {
            get {
                return ResourceManager.GetString("copyleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на © copied to the clipboard!.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text decoded!.
        /// </summary>
        internal static string decodedFromBaseTray {
            get {
                return ResourceManager.GetString("decodedFromBaseTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result is: &quot;.
        /// </summary>
        internal static string decodedFromBaseTray2 {
            get {
                return ResourceManager.GetString("decodedFromBaseTray2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Digits+Letters.
        /// </summary>
        internal static string diggits_letters {
            get {
                return ResourceManager.GetString("diggits_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numbers.
        /// </summary>
        internal static string digits {
            get {
                return ResourceManager.GetString("digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  done....
        /// </summary>
        internal static string doneWithDots {
            get {
                return ResourceManager.GetString("doneWithDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File size = .
        /// </summary>
        internal static string fg_fileSize {
            get {
                return ResourceManager.GetString("fg_fileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files ready:.
        /// </summary>
        internal static string fg_filesReady {
            get {
                return ResourceManager.GetString("fg_filesReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is too big and further glitching will cause error.\nPlease take another file..
        /// </summary>
        internal static string fg_fileTooBig {
            get {
                return ResourceManager.GetString("fg_fileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is too small to work with it..
        /// </summary>
        internal static string fg_fileTooSmall {
            get {
                return ResourceManager.GetString("fg_fileTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitching ratio (1 - fully, 100 - 1/100 etc).
        /// </summary>
        internal static string fg_glitchingRatio {
            get {
                return ResourceManager.GetString("fg_glitchingRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This programm has limit - 500 MB for one glitching file, because bigger size can make your PC explode. Tested..
        /// </summary>
        internal static string fg_limit {
            get {
                return ResourceManager.GetString("fg_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mismatch of ratio and file size!.
        /// </summary>
        internal static string fg_mismatchOfSizes {
            get {
                return ResourceManager.GetString("fg_mismatchOfSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of glitching blocks:.
        /// </summary>
        internal static string fg_numberOfGlitchingBlocks {
            get {
                return ResourceManager.GetString("fg_numberOfGlitchingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something wrong with file path!.
        /// </summary>
        internal static string fg_pathError {
            get {
                return ResourceManager.GetString("fg_pathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start byte is bigger/equal to file size. Please choose less start byte.
        /// </summary>
        internal static string fg_startByteWarning {
            get {
                return ResourceManager.GetString("fg_startByteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose less glitching blocks! Max number now is .
        /// </summary>
        internal static string fg_takeLessGlitchingBlocks {
            get {
                return ResourceManager.GetString("fg_takeLessGlitchingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose less glitching bytes in block!.
        /// </summary>
        internal static string fg_takeLessGlitchingBytes {
            get {
                return ResourceManager.GetString("fg_takeLessGlitchingBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wait! Work in progress....
        /// </summary>
        internal static string fg_waiting {
            get {
                return ResourceManager.GetString("fg_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate.
        /// </summary>
        internal static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch.
        /// </summary>
        internal static string glitch {
            get {
                return ResourceManager.GetString("glitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch extent:.
        /// </summary>
        internal static string glitchExtent {
            get {
                return ResourceManager.GetString("glitchExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch extent must be smaller that text length, or input text is empty!.
        /// </summary>
        internal static string glitchExtentWarning {
            get {
                return ResourceManager.GetString("glitchExtentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now I&apos;m in tray!.
        /// </summary>
        internal static string inTray {
            get {
                return ResourceManager.GetString("inTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invisible symbol copied to clipboard!.
        /// </summary>
        internal static string invisible {
            get {
                return ResourceManager.GetString("invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s not Base64!.
        /// </summary>
        internal static string itsNotBase {
            get {
                return ResourceManager.GetString("itsNotBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to decode it, because this is note Base64..
        /// </summary>
        internal static string itsNotBase2 {
            get {
                return ResourceManager.GetString("itsNotBase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keys generated: .
        /// </summary>
        internal static string keysGenerated {
            get {
                return ResourceManager.GetString("keysGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lenny Face copied to the clipboard!.
        /// </summary>
        internal static string lenface {
            get {
                return ResourceManager.GetString("lenface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Letters.
        /// </summary>
        internal static string letters {
            get {
                return ResourceManager.GetString("letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light-glitch.
        /// </summary>
        internal static string lightGlitch {
            get {
                return ResourceManager.GetString("lightGlitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✔ copied to the clipboard!.
        /// </summary>
        internal static string mark {
            get {
                return ResourceManager.GetString("mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace.
        /// </summary>
        internal static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reverse.
        /// </summary>
        internal static string reverse {
            get {
                return ResourceManager.GetString("reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ¯\_(ツ)_/¯ copied to the clipboard!.
        /// </summary>
        internal static string shrug {
            get {
                return ResourceManager.GetString("shrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size: .
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writen on C#. Author and code: t.me/russkiypoopforever..
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphics: t.me/naturalnonsense..
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/DBmain/TextOGlitch.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ™ copied to the clipboard!.
        /// </summary>
        internal static string trademark {
            get {
                return ResourceManager.GetString("trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word size:.
        /// </summary>
        internal static string wordSize {
            get {
                return ResourceManager.GetString("wordSize", resourceCulture);
            }
        }
    }
}
