//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextOGlitch_3 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextOGlitch_3.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text&apos;O&apos;Glitch Experimental.
        ///Writen on C#. Author and code: t.me/russkiypoopforever.
        ///Graphics: t.me/naturalnonsense.
        ///https://github.com/DBmain/TextOGlitch.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clipboard is empty!.
        /// </summary>
        internal static string clipboardEmpty {
            get {
                return ResourceManager.GetString("clipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text converted to Base64!.
        /// </summary>
        internal static string convertedToBaseTray {
            get {
                return ResourceManager.GetString("convertedToBaseTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied to clipboard..
        /// </summary>
        internal static string copiedToClipboard {
            get {
                return ResourceManager.GetString("copiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ® copied to the clipboard!.
        /// </summary>
        internal static string copyleft {
            get {
                return ResourceManager.GetString("copyleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на © copied to the clipboard!.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text decoded!.
        /// </summary>
        internal static string decodedFromBaseTray {
            get {
                return ResourceManager.GetString("decodedFromBaseTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result is: &quot;.
        /// </summary>
        internal static string decodedFromBaseTray2 {
            get {
                return ResourceManager.GetString("decodedFromBaseTray2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glitch extent:.
        /// </summary>
        internal static string glitchExtent {
            get {
                return ResourceManager.GetString("glitchExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now I&apos;m in tray!.
        /// </summary>
        internal static string inTray {
            get {
                return ResourceManager.GetString("inTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invisible symbol copied to clipboard!.
        /// </summary>
        internal static string invisible {
            get {
                return ResourceManager.GetString("invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That&apos;s not Base64!.
        /// </summary>
        internal static string itsNotBase {
            get {
                return ResourceManager.GetString("itsNotBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to decode it, because this is note Base64..
        /// </summary>
        internal static string itsNotBase2 {
            get {
                return ResourceManager.GetString("itsNotBase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lenny Face copied to the clipboard!.
        /// </summary>
        internal static string lenface {
            get {
                return ResourceManager.GetString("lenface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✔ copied to the clipboard!.
        /// </summary>
        internal static string mark {
            get {
                return ResourceManager.GetString("mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ¯\_(ツ)_/¯ copied to the clipboard!.
        /// </summary>
        internal static string shrug {
            get {
                return ResourceManager.GetString("shrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size:.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ™ copied to the clipboard!.
        /// </summary>
        internal static string trademark {
            get {
                return ResourceManager.GetString("trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word size:.
        /// </summary>
        internal static string wordSize {
            get {
                return ResourceManager.GetString("wordSize", resourceCulture);
            }
        }
    }
}
